### ISSUE TITLE
API questions / problems

### ISSUE THREAD

**Issue by segeljakt** [rust-lang/ena#32]
Hi, I'm using ena for type inference it works excellently but I got some questions:

* After type inference, using the `UnificationTable` as a side-table for looking up type information is cumbersome since `probe_value` takes `&mut self`, does it need to?

* Maybe it would be better if I convert the `UnificationTable` into a `Vec<Value>` indexed by `Key`, or `HashMap<Key, Value>`. In this case, it would be useful to know the number of roots in the `UnificationTable` so I can pre-allocate the capacity, but I could not find a method for it. Would it make sense to add this or not?

* Would you recommend storing type information this way, or is it better to store it directly in AST nodes?

**Comment by nikomatsakis** [comment]
@segeljakt lol sorry I am so slow to notice this notification. A few quick answers

* probe-value does need mut self because of path compression. That is, it may make changes to make repeated lookups faster (this is a key part of the algorithm). It could be written perhaps to use a ref-cell.

* The number of roots -- I guess it'd be easy enough to maintain this information. I'm a bit reluctant to add it but only because I'd sort of like to do a thorough review of how/where ena is being used and overhaul it into something more maintainable. I suppose the overhead of a single field wouldn't be so bad.

* Storing type information -- what we do in rustc and elsewhere is, after some point, to remove all inference variables and just store the "fully resolved" types. That's probably useful in terms of avoiding  the need to thread around the table information

Anyway as you can probably tell from the lagginess of my reply ena is to some extent an "implementation detail" of rustc at this point and I think not very thoroughly maintained as its own library, for better or worse. IF you'd like to make extensive changes, honestly, forking might be a better path for now.

**Comment by segeljakt** [comment]
Sorry, I should have responded earlier also. Thank you for the answer. A ref-cell was able to solve my problems.
